>>> mul = __import__("101-lazy_matrix_mul").lazy_matrix_mul

>>> m_a = [[2, 3, 4], [1, 2, 3]]
>>> m_b =[[1, 2, 3], [2, 4, 6], [3, 2, 1]]

>>> mul(m_a, m_b)
array([[20, 24, 28],
       [14, 16, 18]])

>>> mul("foo", m_b)
Traceback (most recent call last):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'matmul' did not contain a loop with signature matching types (dtype('<U3'), dtype('int64')) -> None

>>> mul(m_a, "spam")
Traceback (most recent call last):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'matmul' did not contain a loop with signature matching types (dtype('int64'), dtype('<U4')) -> None

>>> mul([1, 3, 4], m_b)
array([19, 22, 25])

>>> mul(m_a, [2, 5, 6])
array([43, 30])

>>> mul([], m_b)
Traceback (most recent call last):
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 0)

>>> mul(m_a, [[]])
Traceback (most recent call last):
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

>>> mul([['foo', 'faf'], ['far', 'foo']], m_b)
Traceback (most recent call last):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'matmul' did not contain a loop with signature matching types (dtype('<U3'), dtype('int64')) -> None

>>> mul(m_a, [['foo', 'faf'], ['far', 'foo']])
Traceback (most recent call last):
numpy.core._exceptions._UFuncNoLoopError: ufunc 'matmul' did not contain a loop with signature matching types (dtype('int64'), dtype('<U3')) -> None

>>> m_b.append([5, 4])
>>> mul(m_b, m_a)
Traceback (most recent call last):
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

>>> mul(m_a, m_b)
Traceback (most recent call last):
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

>>> mul(m_a, m_a)
Traceback (most recent call last):
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

>>> mul(m_a)
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

>>> mul()
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'
